### PR TITLE
ui: Add login page screen.

### PR DESCRIPTION
**Pull request by akarsh-jain-790**
Screenshot 2023-05-27 at 7 04 29 PM 1

### CODE REVIEW

**Comment by akarsh-jain-790** [comment]
@luismir15 I was attempting to design something similar to this https://dribbble.com/shots/14002215-Dog-Adoption-App. Please let me know if you have any suggestions regarding the design. Currently, I have used a temporary logo, and will update the logo and name at a later stage.

**Review by luismir15 — APPROVED** [review]
nice work!!

**Comment by luismir15** [comment]
@akarsh-jain-790 Minor bug but when I go ahead to type on the field I'm getting a warning on my phone. Yet, in the simulator I don't seem to get it which it's odd. 
image

**Comment by luismir15** [comment]
image

**Comment by akarsh-jain-790** [comment]
@luismir15 I fixed the issue by adding a ScrollView as a parent.

**Review by luismir15 — COMMENTED** [review]
awesome!!

**Pull request merged**
